#
# Makefile for the Atheros WLAN driver.
#

obj ?= .
src ?= .
srctree ?= .

TOP = $(srctree)/$(src)/..

COMPAT=	$(TOP)/include

INCS = -include $(COMPAT)/compat.h -I$(COMPAT)
INCS += -I$(TOP) -I$(HAL)

EXTRA_CFLAGS += $(INCS)

obj-$(CONFIG_ATHEROS) += ath_hal.o
ath_hal-objs := ah_osdep.o ar5xxx.o ar5212.o ar5211.o ar5210.o \
	ieee80211_regdomain.o
